version: "3"

services:

  db:
    image: "mysql:8.0.33"
    container_name: db
    ports:
      - 3306:3306
    # restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: root
      # MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: fms

  fmsserver:
    # build: ./my_super_app
    image: "alsk1369854/fmsserver"
    container_name: fmsserver
    ports:
      - 8080:8080
    # restart: always
    links:
      - db:db
    depends_on:
      - db
    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  adminer:
    image: adminer
    ports:
      - 8880:8080
